"""
Script gộp tất cả file A-Z.txt thành hardcoded C# string
Output: WordListRules.cs với const string
"""

import os
import re

def escape_csharp_string(s):
    """Escape chuỗi cho C# verbatim string literal"""
    return s.replace("\\", "\\\\").replace("\"", "\"\"")

def main():
    rules_dir = r'R:\HDD R\ZC SYMLINK\USERS\source\repos\ghostminhtoan\Subtitle draft GMTPC CS\english word rules karaoke'
    output_file = r'R:\HDD R\ZC SYMLINK\USERS\source\repos\ghostminhtoan\Subtitle draft GMTPC CS\Services\WordListRules.cs'
    
    if not os.path.exists(rules_dir):
        print(f"Không tìm thấy: {rules_dir}")
        return
    
    all_rules = []
    
    for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
        filepath = os.path.join(rules_dir, f'{letter}.txt')
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Trích xuất rules từ format: (word:part1/part2)
            matches = re.findall(r'\(([^)]+)\)', content)
            if matches:
                all_rules.extend(matches)
            else:
                # Fallback: mỗi dòng là 1 rule
                for line in content.split('\n'):
                    line = line.strip()
                    if line:
                        all_rules.append(line)
    
    # Tạo C# file với hardcoded string
    rules_text = '\n'.join(all_rules)
    escaped = escape_csharp_string(rules_text)
    
    csharp_code = f'''// Auto-generated by embed_word_rules.py - DO NOT EDIT MANUALLY
// Generated: {len(all_rules)} rules from A-Z.txt

namespace Subtitle_draft_GMTPC.Services
{{
    public static class WordListRules
    {{
        public const string DefaultRules = @"{escaped}";
    }}
}}
'''
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(csharp_code)
    
    print(f"✅ Generated {output_file}")
    print(f"📊 Total rules: {len(all_rules)}")
    print(f"📏 String length: {len(rules_text)} chars")

if __name__ == '__main__':
    main()
